version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: realestateportal-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./data/properties.json:/docker-entrypoint-initdb.d/properties.json:ro

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: realestateportal-backend
    restart: always
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDatabase__ConnectionString=mongodb://mongo:27017
      - MongoDatabase__DatabaseName=RealEstateDb
    ports:
      - "5050:8080"   # Swagger API
    volumes:
      - ./data/properties.json:/app/data/properties.json:ro

  # frontend:
  #   build: ./FrontEnd
  #   container_name: realestateportal-frontend
  #   restart: always
  #   depends_on:
  #     - backend
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://backend:8080
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./FrontEnd:/src

volumes:
  mongo_data:
